# Generated by Django 5.2.7 on 2025-10-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfiles',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
