# Generated by Django 5.2.7 on 2025-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oidc_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
