# Generated by Django 5.2.7 on 2025-10-27 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='zip_file',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_comments', to=settings.AUTH_USER_MODEL)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
        ),
        migrations.CreateModel(
            name='ModVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50)),
                ('zip_file', models.FileField(upload_to='mods/')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
        ),
    ]
