# Generated by Django 5.2.7 on 2025-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_mod_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='modversion',
            name='changelog',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
