# Generated by Django 5.2.7 on 2025-10-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0005_mod_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='modversion',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
